# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
