# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 08:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0002_client_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='collect_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='created',
            field=models.DateField(null=True, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='client',
            name='delivery_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_home',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_work',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='client',
            name='type_account',
            field=models.CharField(choices=[('Client', 1), ('Deliver', 2)], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
