# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20171124_0822'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
            ],
        ),
    ]
