# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20171124_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('url', models.URLField(default='http://', max_length=255, null=True)),
                ('image', models.ImageField(height_field=500, upload_to='', width_field=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='photo',
        ),
        migrations.AddField(
            model_name='client',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Image'),
        ),
    ]
