# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20171129_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='delivery_phone',
        ),
        migrations.AlterField(
            model_name='client',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Image', verbose_name='photos'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/upload/'),
        ),
    ]
