# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20171130_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='type_account',
            field=models.CharField(choices=[(1, 'Client'), (2, 'Deliver')], max_length=10, null=True),
        ),
    ]
