# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20171130_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='images',
        ),
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Image', verbose_name='photo'),
        ),
    ]
