# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20171130_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
