# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0012_auto_20171130_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('deliver_phone', models.CharField(max_length=255)),
                ('delivery_address', models.CharField(max_length=255)),
                ('delivery_status', models.IntegerField(choices=[(0, 'In progress'), (1, 'In way'), (2, 'Cancel'), (3, 'Delivered')], default=0)),
                ('show', models.BooleanField(default=1)),
                ('geo_location', models.CharField(max_length=255, null=True)),
                ('ip', models.CharField(max_length=255, null=True)),
                ('created', models.DateTimeField(verbose_name='cretae delivery time')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
                ('pictures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Image')),
            ],
        ),
    ]
