# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Deliverie'},
        ),
    ]
